# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: actionsms 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "actionsms"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roman Shterenzon"]
  s.date = "2015-04-12"
  s.description = "Like ActionMailer, but for SMS"
  s.email = "romanbsd@yahoo.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "actionsms.gemspec",
    "lib/actionsms.rb",
    "lib/sms.rb",
    "lib/sms/log_subscriber.rb",
    "lib/sms/message.rb",
    "lib/sms/method/bezeq.rb",
    "lib/sms/method/file.rb",
    "lib/sms/method/gsm.rb",
    "lib/sms/method/kannel.rb",
    "lib/sms/method/twilio.rb",
    "spec/sms/message_spec.rb",
    "spec/sms/method/bezeq_spec.rb",
    "spec/sms_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/romanbsd/actionsms"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Like ActionMailer, but for SMS"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2.0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.2"])
      s.add_dependency(%q<rspec>, ["~> 3.2.0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.2"])
    s.add_dependency(%q<rspec>, ["~> 3.2.0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

